In [3]:
#Import python libraries
import numpy as np

In [8]:
#Create euclidean distance function
def euclidean_distance(x1,x2):
  return np.sqrt(np.sum((x1 - x2)**2));

In [9]:
#Dummy data to test the distance formula
x1 = np.array([[5, 4], [3,2], [1,7]])
x2 = np.array([[3,2], [5,3], [1,6]])

In [11]:
#print the distance result
print(euclidean_distance(x1,x2))

3.7416573867739413


In [12]:
#Create a class KNN along with methods to predict the result
class KNN:
  def __init__(self, k = 3):
    self.k = k

  def fit(self, x, y):
    self.x = x
    self.y = y

  def predict(self, x):
    predictions = []
    for x in x:
      prediction = self._predict(x)
      predictions.append(prediction)
    return predictions

  def _predict(self, x): #helper function
    distances = []
    for x_i in self.x:
      distance = euclidean_distance(x, x_i)
      distances.append(distance)

    indices = np.argsort(distances)
    indices  = indices[ : self.k]
    label = self.most_common_label(self.y[indices])
    return label

  def most_common_label(self, y):
    labels, counts = np.unique(y, return_counts=True)
    return labels[np.argmax(counts)]

In [15]:
#Create dummy data 
x = np.array([[1,2], [2,3], [3,4], [4,5], [5,6]])
print(x)
y = np.array([1, 1, 0, 0, 0])
print(y)

[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [5 6]]
[1 1 0 0 0]


In [16]:
#Train the model
model = KNN()
model.fit(x, y)

In [17]:
#Test the model
prediction = model.predict(x)

In [18]:
#Check the result
print(prediction)
print(y)

[1, 1, 0, 0, 0]
[1 1 0 0 0]
