In [5]:
import numpy as np

In [6]:
#Create a class Support Vector Machine(SVM) along with all functions to predict the result
class SVM:
  def __init__(self, learning_rate, C, n_iters):
    self.learning_rate = learning_rate
    self.C = C
    self.n_iters = n_iters
    self.weights = None
    self.bias = None

  def  fit(self, x, y):
    samples, features = x.shape
    y = np.where(y <= 0, -1, 1)
    self.weights = np.zeros(features)
    self.bias = 0

    for i in range(self.n_iters):
      for idx, sample in enumerate(x):
        condition = y[idx] * (np.dot(sample, self.weights) - self.bias) >= 1
        if condition:
          self.weights -= self.learning_rate * (2 * self.C * self.weights)
        else:
          self.weights -= self.learning_rate * (2 * self.C * self.weights - np.dot(sample, y[idx]))
          self.bias -= self.learning_rate * y[idx]

  def predict(self, x):
    return np.sign(np.dot(x, self.weights) - self.bias)



In [7]:
#Create a dummy dataset
x = np.array([[2,3],[1,1],[2,1],[4,5],[5,4],[6,6]])
print(x)
y = np.array([-1,-1,-1,1,1,1])
print(y)

[[2 3]
 [1 1]
 [2 1]
 [4 5]
 [5 4]
 [6 6]]
[-1 -1 -1  1  1  1]


In [8]:
#Train the model
model = SVM(learning_rate=0.01, C=0.001, n_iters=1000)
model.fit(x,y)

In [9]:
#Test the model
prediction = model.predict(x)
print(prediction)

[-1. -1. -1.  1.  1.  1.]


In [10]:
#Create a accuracy function to check the result
def accuracy(y, y_predict):
  return np.mean(y == y_predict) * 100

In [11]:
#check the result

In [12]:
print(accuracy(y, prediction))

100.0


Testing with real dataset


In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from  sklearn.model_selection import train_test_split

data = pd.read_csv("../../Datasets/winequality-total.csv", sep = ";")
df = pd.DataFrame(data)
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [17]:
#Separate the dataset into x and y
X= df.iloc[:,:-1]
Y= df.iloc[:,-1]
Y = np.where(Y <= 5, -1, 1)
print(X.shape)
print(Y.shape)

(6497, 11)
(6497,)


In [18]:
#Split dataset into train and test dataset
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)