In [2]:
import numpy as np

In [4]:
#Create a class Support Vector Machine(SVM) along with all functions to predict the result
class SVM:
  def __init__(self, learning_rate, C, n_iters):
    self.learning_rate = learning_rate
    self.C = C
    self.n_iters = n_iters
    self.weights = None
    self.bias = None

  def  fit(self, x, y):
    samples, features = x.shape
    y = np.where(y <= 0, -1, 1)
    self.weights = np.zeros(features)
    self.bias = 0

    for i in range(self.n_iters):
      for idx, sample in enumerate(x):
        condition = y[idx] * (np.dot(sample, self.weights) - self.bias) >= 1
        if condition:
          self.weights -= self.learning_rate * (2 * self.C * self.weights)
        else:
          self.weights -= self.learning_rate * (2 * self.C * self.weights - np.dot(sample, y[idx]))
          self.bias -= self.learning_rate * y[idx]

  def predict(self, x):
    return np.sign(np.dot(x, self.weights) - self.bias)



In [6]:
#Create a dummy dataset
x = np.array([[2,3],[1,1],[2,1],[4,5],[5,4],[6,6]])
print(x)
y = np.array([-1,-1,-1,1,1,1])
print(y)

[[2 3]
 [1 1]
 [2 1]
 [4 5]
 [5 4]
 [6 6]]
[-1 -1 -1  1  1  1]


In [9]:
#Train the model
model = SVM(learning_rate=0.01, C=0.001, n_iters=1000)
model.fit(x,y)

In [10]:
#Test the model
prediction = model.predict(x)
print(prediction)

[-1. -1. -1.  1.  1.  1.]


In [11]:
#Create a accuracy function to check the result
def accuracy(y, y_predict):
  return np.mean(y == y_predict) * 100

In [12]:
#check the result

In [13]:
print(accuracy(y, prediction))

100.0
