In [8]:
import numpy as np

In [9]:
#Define relu and relu derivative function
def relu(x):
  return np.maximum(x, 0)

def relu_derivative(x):
  return np.where(x > 0, 1 , 0)

In [10]:
#Dummy dataset
x = np.array([[1,0,1], [0,1,1], [0,0,1], [1,1,1]])
print(x)
y=np.array([[1, 1, 0, 0]]).T
print(y)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [11]:
#Initialize parameters 
alpha = 0.1  #learning_rate
hidden_layer_size = 3
n_sample, n_features = x.shape
w01 = np.random.random((n_features, hidden_layer_size))
w12 = np.random.random((hidden_layer_size, 1))

In [12]:
#create a logic that perform the forward to predict the result and backward to improve the weight in every layer by updating each weight 
for i in range(100):
  layer_2_error = 0
  for j in range(len(x)):
    layer_0 = x[j : j+1]
    layer_1 = relu(np.dot(layer_0, w01))
    layer_2 = np.dot(layer_1, w12)  #layer_2 = final layer  = y_prediction
    layer_2_error += np.sum((layer_2 - y[i:i+1]) ** 2)
    layer_2_delta = layer_2 - y[j : j+1]
    layer_1_delta = np.dot(layer_2_delta, w12.T) * relu_derivative(layer_1)
    w12 = w12 - alpha * np.dot(layer_1.reshape(-1, 1), layer_2_delta)
    w01 = w01 - alpha * np.dot(layer_0.T, layer_1_delta)
    if(i % 10 == 0):
      print("Error:" + str(layer_2_error))

Error:1.6419869460362928
Error:1.6613285440234271
Error:1.829007040221234
Error:1.950871839042465
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0


In [13]:
#
alpha = 0.1
hidden_size_1 = 4
hidden_size_2 = 3
weights_0_1 = np.random.random((3, hidden_size_1))
weights_1_2 = np.random.random((hidden_size_1, hidden_size_2))
weights_2_3 = np.random.random((hidden_size_2, 1))

In [14]:
for iteration in range(100):
  layer_3_error = 0
  for i in range(len(x)):
    layer_0 = x[i:i+1]
    layer_1 = relu(np.dot(layer_0,weights_0_1))
    layer_2 = relu(np.dot(layer_1,weights_1_2))
    layer_3 = np.dot(layer_2,weights_2_3)
    layer_3_error += np.sum((layer_3 - y[i:i+1]) ** 2)
    layer_3_delta = (layer_3 - y[i:i+1])
    layer_2_delta = np.dot(layer_3_delta, weights_2_3.T)*relu_derivative(layer_2)
    layer_1_delta = np.dot(layer_2_delta, weights_1_2.T)*relu_derivative(layer_1)
    weights_2_3 -= alpha * np.dot(layer_2.T, layer_3_delta)
    weights_1_2 -= alpha * np.dot(layer_1.T, layer_2_delta)
    weights_0_1 -= alpha * np.dot(layer_0.T, layer_1_delta)
    if(iteration % 10 == 0):
      print("Error:" + str(layer_3_error))

Error:3.7801336577137232
Error:3.8392908800427508
Error:3.8783062261439114
Error:4.499278790864503
Error:0.7812191577240026
Error:0.9971551790072506
Error:1.0313306294966904
Error:1.3623484067360958
Error:0.5434575451531675
Error:0.5937812924319879
Error:0.6442824834569318
Error:0.8878190037417146
Error:0.2964327928375061
Error:0.31349821040887593
Error:0.334702237011933
Error:0.4896013903143852
Error:0.05976654638383402
Error:0.061319345511435294
Error:0.0776006436406083
Error:0.1346580824501355
Error:0.004296559170459562
Error:0.0043336475821615155
Error:0.010184993031775526
Error:0.028317585853804873
Error:0.0006885695365288767
Error:0.0007064816124774326
Error:0.0016848875486833153
Error:0.007608899655943943
Error:0.00019097495436804562
Error:0.00019342369777156237
Error:0.0002974291594276025
Error:0.002445880942701083
Error:3.148045557394463e-05
Error:7.411240597433118e-05
Error:9.243388766140329e-05
Error:0.0008688762166303821
Error:9.035274196656593e-06
Error:1.0188905148768485e