In [20]:
import numpy as np

In [21]:
#Define relu and relu derivative function
def relu(x):
  return np.max(x, 0)

def relu_derivative(x):
  return np.where(x > 0, 1 , 0)

In [22]:
#Dummy dataset
x = np.array([[1,0,1], [0,1,1], [0,0,1], [1,1,1]])
print(x)
y=np.array([[1, 1, 0, 0]]).T
print(y)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [23]:
#Initialize parameters 
alpha = 0.1  #learning_rate
hidden_layer_size = 3
n_sample, n_features = x.shape
w01 = np.random.random((n_features, hidden_layer_size))
w12 = np.random.random((hidden_layer_size, 1))

In [24]:
#create a logic that perform the forward to predict the result and backward to improve the weight in every layer by updating each weight 
for i in range(100):
  layer_2_error = 0
  for j in range(len(x)):
    layer_0 = x[j : j+1]
    layer_1 = relu(np.dot(layer_0, w01))
    layer_2 = np.dot(layer_1, w12)  #layer_2 = final layer  = y_prediction
    layer_2_error += np.sum((layer_2 - y[i:i+1]) ** 2)
    layer_2_delta = layer_2 - y[j : j+1]
    layer_1_delta = np.dot(layer_2_delta, w12.T) * relu_derivative(layer_1)
    w12 = w12 - alpha * np.dot(layer_1.reshape(-1, 1), layer_2_delta)
    w01 = w01 - alpha * np.dot(layer_0.T, layer_1_delta)
    if(i % 10 == 0):
      print("Error:" + str(layer_2_error))

Error:3.1030582105135425
Error:3.1056831667040776
Error:3.4453938904772965
Error:4.284165820423253
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0


In [25]:
#
alpha = 0.1
hidden_size_1 = 4
hidden_size_2 = 3
weights_0_1 = np.random.random((3, hidden_size_1))
weights_1_2 = np.random.random((hidden_size_1, hidden_size_2))
weights_2_3 = np.random.random((hidden_size_2, 1))

In [26]:
for iteration in range(100):
  layer_3_error = 0
  for i in range(len(x)):
    layer_0 = x[i:i+1]
    layer_1 = relu(np.dot(layer_0,weights_0_1))
    layer_2 = relu(np.dot(layer_1,weights_1_2))
    layer_3 = np.dot(layer_2,weights_2_3)
    layer_3_error += np.sum((layer_3 - y[i:i+1]) ** 2)
    layer_3_delta = (layer_3 - y[i:i+1])
    layer_2_delta = np.dot(layer_3_delta, weights_2_3.T)*relu_derivative(layer_2)
    layer_1_delta = np.dot(layer_2_delta, weights_1_2.T)*relu_derivative(layer_1)
    weights_2_3 -= alpha * np.dot(layer_2.T, layer_3_delta)
    weights_1_2 -= alpha * np.dot(layer_1.T, layer_2_delta)
    weights_0_1 -= alpha * np.dot(layer_0.T, layer_1_delta)
    if(iteration % 10 == 0):
      print("Error:" + str(layer_3_error))

ValueError: shapes (4,) and (3,3) not aligned: 4 (dim 0) != 3 (dim 0)