In [9]:
import numpy as np

In [10]:
#Define relu and relu derivative function
def relu(x):
  return np.max(x, 0)

def relu_derivative(x):
  return np.where(x > 0, 1 , 0)

In [11]:
#Dummy dataset
x = np.array([[1,0,1], [0,1,1], [0,0,1], [1,1,1]])
print(x)
y=np.array([[1, 1, 0, 0]]).T
print(y)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [12]:
#Initialize parameters 
alpha = 0.1  #learning_rate
hidden_layer_size = 3
n_sample, n_features = x.shape
w01 = np.random.random((n_features, hidden_layer_size))
w12 = np.random.random((hidden_layer_size, 1))

In [13]:
#create a logic that perform the forward to predict the result and backward to improve the weight in every layer by updating each weight 
for i in range(100):
  layer_2_error = 0
  for j in range(len(x)):
    layer_0 = x[j : j+1]
    layer_1 = relu(np.dot(layer_0, w01))
    layer_2 = np.dot(layer_1, w12)  #layer_2 = final layer  = y_prediction
    layer_2_error += np.sum((layer_2 - y[i:i+1]) ** 2)
    layer_2_delta = layer_2 - y[j : j+1]
    layer_1_delta = np.dot(layer_2_delta, w12.T) * relu_derivative(layer_1)
    w12 = w12 - alpha * np.dot(layer_1.reshape(-1, 1), layer_2_delta)
    w01 = w01 - alpha * np.dot(layer_0.T, layer_1_delta)
    if(i % 10 == 0):
      print("Error:" + str(layer_2_error))

Error:0.032184243062676886
Error:0.2066614022289797
Error:0.5801400885502916
Error:0.6746409003786835
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
