In [5]:
import numpy as np

In [6]:
#Define relu and relu derivative function
def relu(x):
  return np.max(x, 0)

def relu_derivative(x):
  return np.where(x > 0, 1 , 0)

In [7]:
#Dummy dataset
x = np.array([[1,0,1], [0,1,1], [0,0,1], [1,1,1]])
print(x)
y=np.array([[1, 1, 0, 0]]).T
print(y)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [8]:
#Initialize parameters 
alpha = 0.1  #learning_rate
hidden_layer_size = 3
n_sample, n_features = x.shape
w01 = np.random.random((n_features, hidden_layer_size))
w12 = np.random.random((hidden_layer_size, 1))