In [1]:
import numpy as np

In [2]:
#Define relu and relu derivative function
def relu(x):
  return np.maximum(x, 0)

def relu_derivative(x):
  return np.where(x > 0, 1 , 0)

In [3]:
#Dummy dataset
x = np.array([[1,0,1], [0,1,1], [0,0,1], [1,1,1]])
print(x)
y=np.array([[1, 1, 0, 0]]).T
print(y)

[[1 0 1]
 [0 1 1]
 [0 0 1]
 [1 1 1]]
[[1]
 [1]
 [0]
 [0]]


In [4]:
#Initialize parameters 
alpha = 0.1  #learning_rate
hidden_layer_size = 3
n_sample, n_features = x.shape
w01 = np.random.random((n_features, hidden_layer_size))
w12 = np.random.random((hidden_layer_size, 1))

In [5]:
#create a logic that perform the forward to predict the result and backward to improve the weight in every layer by updating each weight 
for i in range(100):
  layer_2_error = 0
  for j in range(len(x)):
    layer_0 = x[j : j+1]
    layer_1 = relu(np.dot(layer_0, w01))
    layer_2 = np.dot(layer_1, w12)  #layer_2 = final layer  = y_prediction
    layer_2_error += np.sum((layer_2 - y[i:i+1]) ** 2)
    layer_2_delta = layer_2 - y[j : j+1]
    layer_1_delta = np.dot(layer_2_delta, w12.T) * relu_derivative(layer_1)
    w12 = w12 - alpha * np.dot(layer_1.reshape(-1, 1), layer_2_delta)
    w01 = w01 - alpha * np.dot(layer_0.T, layer_1_delta)
    if(i % 10 == 0):
      print("Error:" + str(layer_2_error))

Error:0.20957630739781027
Error:0.21003346397928951
Error:0.41016450692322604
Error:0.5879505554177367
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0
Error:0.0


In [6]:
#
alpha = 0.1
hidden_size_1 = 4
hidden_size_2 = 3
weights_0_1 = np.random.random((3, hidden_size_1))
weights_1_2 = np.random.random((hidden_size_1, hidden_size_2))
weights_2_3 = np.random.random((hidden_size_2, 1))

In [7]:
for iteration in range(100):
  layer_3_error = 0
  for i in range(len(x)):
    layer_0 = x[i:i+1]
    layer_1 = relu(np.dot(layer_0,weights_0_1))
    layer_2 = relu(np.dot(layer_1,weights_1_2))
    layer_3 = np.dot(layer_2,weights_2_3)
    layer_3_error += np.sum((layer_3 - y[i:i+1]) ** 2)
    layer_3_delta = (layer_3 - y[i:i+1])
    layer_2_delta = np.dot(layer_3_delta, weights_2_3.T)*relu_derivative(layer_2)
    layer_1_delta = np.dot(layer_2_delta, weights_1_2.T)*relu_derivative(layer_1)
    weights_2_3 -= alpha * np.dot(layer_2.T, layer_3_delta)
    weights_1_2 -= alpha * np.dot(layer_1.T, layer_2_delta)
    weights_0_1 -= alpha * np.dot(layer_0.T, layer_1_delta)
    if(iteration % 10 == 0):
      print("Error:" + str(layer_3_error))

Error:4.700885273267766
Error:5.219464399136985
Error:5.361077423930598
Error:6.4597483169252685
Error:0.7894249372346733
Error:1.0124285947043992
Error:1.0474128738063857
Error:1.4261388873880452
Error:0.5170574421128131
Error:0.5684166323749337
Error:0.6089242103079751
Error:0.8355360124665526
Error:0.3395407712973342
Error:0.3448062382379559
Error:0.38261415892404194
Error:0.5649178417652505
Error:0.16391142144777998
Error:0.16425527825814715
Error:0.19377945256247564
Error:0.2705288393345009
Error:0.0339872575205732
Error:0.0344166277856734
Error:0.05247024650392527
Error:0.06304420900809435
Error:0.0021637922199740085
Error:0.0021864611161922297
Error:0.00751338906115984
Error:0.01184984825336433
Error:0.00023060337399372484
Error:0.00023073904712343673
Error:0.0011947852389740774
Error:0.004291640456521314
Error:4.1240458434989316e-05
Error:4.2766060282970256e-05
Error:0.0001956372934560993
Error:0.00241672050726108
Error:8.901638436356631e-06
Error:1.0865791751880284e-05
Error:3