In [5]:
import numpy as np

In [ ]:
# Extract or Load data from mnist file 
data = np.load("../Datasets/mnist.npz")

x_train = data["x_train"]
y_train = data["y_train"]
x_test = data["x_test"]
y_test = data["y_test"]

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)


(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [11]:
#Take small set of data for quick training 
x_train = x_train[0:1000]
labels = y_train[0:1000]
x_train = x_train.reshape(1000, 28 * 28 )
images = x_train / 255

In [12]:
# one hot vectors for train
one_hot_vectors = np.zeros((len(labels), 10))
for idx, label in enumerate(labels):
    one_hot_vectors[idx][label] = 1
labels = one_hot_vectors

print(labels)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
#Testing dataset
x_test = x_test.reshape(-1, 28 *28)
x_test = x_test / 255

y_test_one_hot_vectors = np.zeros((len(y_test), 10))

for idx, label in enumerate(y_test):
    y_test_one_hot_vectors[idx][label] = 1

y_test = y_test_one_hot_vectors
print(y_test)

In [ ]:
#Define functions

def tanh(x):
  return np.tanh(x)

def tanh2deriv(output):
  return 1 - (output ** 2)

def softmax(x):
  temp = np.exp(x)
  return temp / np.sum(temp, axis=1, keepdims=True)
